import { useEffect, useRef, useState } from 'react';

interface SimulationModule {
  id: string;
  num: string;
  title: string;
  line1: string;
  line2: string;
  tags: [string, string, string];
  status: string;
  accentColor: string;
  secondaryColor: string;
}

const MODULES: SimulationModule[] = [
  {
    id: 'cfd',
    num: '01',
    title: 'CFD & FLOW ANALYSIS',
    line1: 'Simulate fluid motion to understand velocity, pressure, turbulence and aerodynamic behaviour.',
    line2: 'Analyse how liquids and gases interact with engineering geometries and operating conditions.',
    tags: ['VELOCITY', 'PRESSURE', 'TURBULENCE'],
    status: 'PHYSICS MODULE',
    accentColor: '#03cff4',
    secondaryColor: '#0c8fce',
  },
  {
    id: 'thermal',
    num: '02',
    title: 'THERMAL FLUID ANALYSIS',
    line1: 'Analyse heat transfer together with fluid flow to predict temperature distribution and thermal behaviour.',
    line2: 'Study convection, cooling, heating and fluid–thermal interactions within engineering systems.',
    tags: ['HEAT TRANSFER', 'CONVECTION', 'COOLING'],
    status: 'PHYSICS MODULE',
    accentColor: '#fa9224',
    secondaryColor: '#ffc21c',
  },
  {
    id: 'structural',
    num: '03',
    title: 'STRUCTURAL FEA',
    line1: 'Evaluate how engineering components respond to forces, pressure, constraints and mechanical loads.',
    line2: 'Predict stress, strain and deformation to support safer and more efficient structural designs.',
    tags: ['STRESS', 'STRAIN', 'DEFORMATION'],
    status: 'PHYSICS MODULE',
    accentColor: '#e80874',
    secondaryColor: '#9f04c3',
  },
  {
    id: 'multiphysics',
    num: '04',
    title: 'MULTIPHYSICS ANALYSIS',
    line1: 'Couple multiple physical phenomena when fluid, thermal, structural or other effects influence one another.',
    line2: 'Study complex engineering systems where solving one physics domain independently is not sufficient.',
    tags: ['COUPLED PHYSICS', 'FLUID–THERMAL', 'THERMAL–STRUCTURAL'],
    status: 'PHYSICS MODULE',
    accentColor: '#03cff4',
    secondaryColor: '#9f04c3',
  },
  {
    id: 'multiphase',
    num: '05',
    title: 'MULTIPHASE SIMULATION',
    line1: 'Model systems containing multiple interacting phases such as liquids, gases, droplets, particles or interfaces.',
    line2: 'Investigate mixing, separation, free-surface behaviour and phase interactions in complex flows.',
    tags: ['LIQUID–GAS', 'PARTICLES', 'FREE SURFACE'],
    status: 'PHYSICS MODULE',
    accentColor: '#03cff4',
    secondaryColor: '#9f04c3',
  },
  {
    id: 'acoustics',
    num: '06',
    title: 'ACOUSTICS & NVH',
    line1: 'Analyse sound, vibration and noise behaviour generated by mechanical and fluid systems.',
    line2: 'Identify resonances and acoustic responses to improve comfort, reliability and engineering performance.',
    tags: ['NOISE', 'VIBRATION', 'RESONANCE'],
    status: 'PHYSICS MODULE',
    accentColor: '#0c8fce',
    secondaryColor: '#03cff4',
  },
];

// Custom Technical SVG Illustration for each module
function ModuleTechnicalIcon({ id, accentColor }: { id: string; accentColor: string }) {
  switch (id) {
    case 'cfd':
      return (
        <svg viewBox="0 0 36 36" className="w-8 h-8" fill="none">
          <path d="M4 10 C 14 10, 18 8, 32 8" stroke={accentColor} strokeWidth="1.2" opacity="0.6" strokeDasharray="3 2" />
          <path d="M4 18 C 12 18, 16 14, 22 14 C 28 14, 30 18, 32 18" stroke={accentColor} strokeWidth="1.5" />
          <path d="M4 26 C 14 26, 18 24, 32 24" stroke={accentColor} strokeWidth="1.2" opacity="0.6" strokeDasharray="3 2" />
          <path d="M10 18 Q 16 13, 24 16 Q 16 21, 10 18 Z" fill="rgba(3,207,244,0.18)" stroke={accentColor} strokeWidth="1.2" />
        </svg>
      );
    case 'thermal':
      return (
        <svg viewBox="0 0 36 36" className="w-8 h-8" fill="none">
          <rect x="5" y="8" width="26" height="20" rx="2" stroke="rgba(250,146,36,0.3)" strokeWidth="1" fill="rgba(15,23,42,0.6)" />
          <path d="M8 18 Q 14 14, 18 18 T 28 18" stroke="#03cff4" strokeWidth="1.2" />
          <path d="M8 22 Q 14 18, 18 22 T 28 22" stroke="#ffc21c" strokeWidth="1.2" />
          <path d="M8 25 Q 14 21, 18 25 T 28 25" stroke="#fa9224" strokeWidth="1.4" />
          <path d="M12 12 L12 9 M18 12 L18 9 M24 12 L24 9" stroke="#fa9224" strokeWidth="1.2" strokeLinecap="round" />
        </svg>
      );
    case 'structural':
      return (
        <svg viewBox="0 0 36 36" className="w-8 h-8" fill="none">
          <polygon points="6,28 18,8 30,28" stroke="#e80874" strokeWidth="1.4" fill="rgba(232,8,116,0.1)" />
          <line x1="6" y1="28" x2="24" y2="18" stroke="#e80874" strokeWidth="1" opacity="0.7" />
          <line x1="30" y1="28" x2="12" y2="18" stroke="#e80874" strokeWidth="1" opacity="0.7" />
          <line x1="18" y1="8" x2="18" y2="28" stroke="#e80874" strokeWidth="1" opacity="0.7" />
          <circle cx="18" cy="8" r="1.8" fill="#e80874" />
          <circle cx="6" cy="28" r="1.8" fill="#e80874" />
          <circle cx="30" cy="28" r="1.8" fill="#e80874" />
          <circle cx="18" cy="28" r="1.8" fill="#9f04c3" />
        </svg>
      );
    case 'multiphysics':
      return (
        <svg viewBox="0 0 36 36" className="w-8 h-8" fill="none">
          <circle cx="18" cy="18" r="12" stroke="rgba(3,207,244,0.3)" strokeWidth="1" strokeDasharray="2 2" />
          <circle cx="18" cy="10" r="3.5" fill="rgba(3,207,244,0.3)" stroke="#03cff4" strokeWidth="1.2" />
          <circle cx="26" cy="24" r="3.5" fill="rgba(159,4,195,0.3)" stroke="#9f04c3" strokeWidth="1.2" />
          <circle cx="10" cy="24" r="3.5" fill="rgba(250,146,36,0.3)" stroke="#fa9224" strokeWidth="1.2" />
          <line x1="18" y1="13.5" x2="24" y2="21" stroke="#03cff4" strokeWidth="1" />
          <line x1="23" y1="24" x2="13.5" y2="24" stroke="#9f04c3" strokeWidth="1" />
          <line x1="12" y1="21.5" x2="16.5" y2="13.5" stroke="#fa9224" strokeWidth="1" />
        </svg>
      );
    case 'multiphase':
      return (
        <svg viewBox="0 0 36 36" className="w-8 h-8" fill="none">
          <rect x="5" y="7" width="26" height="22" rx="2" stroke="rgba(3,207,244,0.3)" strokeWidth="1" fill="rgba(15,23,42,0.6)" />
          <path d="M5 18 Q 11 15, 18 18 T 31 18" stroke="#03cff4" strokeWidth="1.4" />
          <circle cx="12" cy="23" r="2.2" stroke="#03cff4" strokeWidth="1.2" fill="rgba(3,207,244,0.2)" />
          <circle cx="23" cy="24" r="1.6" stroke="#9f04c3" strokeWidth="1" fill="rgba(159,4,195,0.2)" />
          <circle cx="20" cy="12" r="1.4" fill="#03cff4" opacity="0.8" />
          <circle cx="14" cy="13" r="1.8" fill="#9f04c3" opacity="0.7" />
        </svg>
      );
    case 'acoustics':
      return (
        <svg viewBox="0 0 36 36" className="w-8 h-8" fill="none">
          <circle cx="12" cy="18" r="3" fill="#0c8fce" stroke="#03cff4" strokeWidth="1" />
          <path d="M17 12 A 8 8 0 0 1 17 24" stroke="#03cff4" strokeWidth="1.2" strokeLinecap="round" />
          <path d="M22 8 A 14 14 0 0 1 22 28" stroke="#03cff4" strokeWidth="1.4" strokeLinecap="round" opacity="0.8" />
          <path d="M27 5 A 19 19 0 0 1 27 31" stroke="#0c8fce" strokeWidth="1.2" strokeLinecap="round" opacity="0.5" strokeDasharray="2 2" />
        </svg>
      );
    default:
      return null;
  }
}

export default function ClassicalSimSection() {
  const [visible, setVisible] = useState(false);
  const sectionRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting) setVisible(true); },
      { threshold: 0.1 }
    );
    if (sectionRef.current) observer.observe(sectionRef.current);
    return () => observer.disconnect();
  }, []);

  return (
    <section id="platform-modules" ref={sectionRef} className="relative py-24 bg-bg-secondary overflow-hidden border-t border-border-subtle">
      <div className="absolute inset-0 grid-bg opacity-25 pointer-events-none" />
      <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_50%_20%,rgba(3,207,244,0.06)_0%,transparent_60%)] pointer-events-none" />

      <div className="relative z-10 max-w-[1520px] mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Section Heading */}
        <div className={`text-center max-w-4xl mx-auto mb-16 transition-all duration-700 ${visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}`}>
          <div className="inline-block px-4 py-1.5 border border-brand-cyan/30 rounded-sm bg-brand-cyan/10 mb-4">
            <span className="font-mono text-xs font-bold text-brand-cyan tracking-[0.2em] uppercase">
              ENGINEERING SIMULATION MODULES
            </span>
          </div>
          <h2 className="text-4xl sm:text-5xl lg:text-6xl font-black text-white tracking-tight">
            WHAT CAN WE <span className="text-gradient-cyan">SIMULATE</span>
          </h2>
        </div>

        {/* 2-Column × 3-Row Module Cards Layout */}
        <div className={`grid grid-cols-1 md:grid-cols-2 gap-5 max-w-6xl mx-auto transition-all duration-700 delay-200 ${visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}`}>
          {MODULES.map((mod) => (
            <div
              key={mod.id}
              onClick={() => document.getElementById('simulation-lab')?.scrollIntoView({ behavior: 'smooth' })}
              className="relative p-6 rounded-sm border border-border-subtle bg-bg-card/90 hover:border-brand-cyan/60 hover:bg-bg-card transition-all duration-200 cursor-pointer group flex flex-col justify-between shadow-lg hover:shadow-[0_0_24px_rgba(3,207,244,0.14)]"
            >
              {/* Top line accent on hover */}
              <div
                className="absolute top-0 left-0 right-0 h-0.5 opacity-0 group-hover:opacity-100 transition-opacity duration-200"
                style={{ background: mod.accentColor }}
              />

              {/* Top Bar: Icon */}
              <div>
                <div className="flex items-center justify-between gap-2 mb-4">
                  <div
                    className="w-11 h-11 rounded-sm flex items-center justify-center p-2 transition-all duration-200 bg-slate-900/80 border border-brand-cyan/20 group-hover:border-brand-cyan/50 group-hover:bg-brand-cyan/10"
                  >
                    <ModuleTechnicalIcon id={mod.id} accentColor={mod.accentColor} />
                  </div>
                </div>

                {/* Module Title */}
                <h3 className="font-bold text-base sm:text-lg text-white tracking-wide group-hover:text-brand-cyan transition-colors mb-2">
                  {mod.title}
                </h3>

                {/* 2-Line Explanation */}
                <p className="text-slate-300 text-xs sm:text-sm leading-relaxed mb-5">
                  {mod.line1} {mod.line2}
                </p>
              </div>

              {/* Bottom: 3 Capability Tags */}
              <div className="pt-3.5 border-t border-border-subtle/70 flex items-center justify-between flex-wrap gap-2">
                <div className="flex flex-wrap gap-1.5">
                  {mod.tags.map((tag) => (
                    <span
                      key={tag}
                      className="font-mono text-[10px] px-2 py-0.5 rounded bg-bg-primary/80 border border-border-subtle text-slate-300"
                    >
                      {tag}
                    </span>
                  ))}
                </div>
              </div>
            </div>
          ))}
        </div>

      </div>
    </section>
  );
}
